public enum BodyPlacement
{
    Head,
    Hair,
    Face,
    LeftEar,
    RightEar,
    Throat,
    Overwear,
    LeftShoulder,
    RightShoulder,
    LeftArm,
    RightArm,
    LeftHand,
    RightHand,
    LeftWrist,
    RightWrist,
    Torso,
    Belt,
    LeftThigh,
    RightThigh,
    LeftShin,
    RightShin,
    LeftFoot,
    RightFoot,
    LeftAnkle,
    RightAnkle,
    LeftFinger1, LeftFinger2, LeftFinger3, LeftFinger4, LeftFinger5,
    RightFinger1, RightFinger2, RightFinger3, RightFinger4, RightFinger5,
    LeftToe1, LeftToe2, LeftToe3, LeftToe4, LeftToe5,
    RightToe1, RightToe2, RightToe3, RightToe4, RightToe5,
    WeaponSlot1,
    WeaponSlot2,
    WeaponSlot3,
    WeaponSlot4
}