// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solace.Database;

#nullable disable

namespace solace.Migrations
{
    [DbContext(typeof(SolaceDbContext))]
    [Migration("20260914145422_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Effects.EffectAffectedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectId")
                        .HasColumnType("integer")
                        .HasColumnName("effect_id");

                    b.Property<int>("StatDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_effect_affected_stats");

                    b.HasIndex("StatDefinitionId")
                        .HasDatabaseName("ix_effect_affected_stats_stat_definition_id");

                    b.HasIndex("EffectId", "StatDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_effect_affected_stats_effect_id_stat_definition_id");

                    b.ToTable("effect_affected_stats", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Effects.EffectsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityAffectedId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_affected_id");

                    b.PrimitiveCollection<int[]>("AffectedBodyPart")
                        .HasColumnType("integer[]")
                        .HasColumnName("affected_body_part");

                    b.Property<int>("DurationRounds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_rounds");

                    b.Property<TimeSpan>("DurationTime")
                        .HasColumnType("interval")
                        .HasColumnName("duration_time");

                    b.Property<bool>("IsInstant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_instant");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ReductionRate")
                        .HasColumnType("integer")
                        .HasColumnName("reduction_rate");

                    b.HasKey("Id")
                        .HasName("pk_effects");

                    b.ToTable("effects", (string)null);
                });

            modelBuilder.Entity("Solace.Models.HexMaps.HexTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HexTileType")
                        .HasColumnType("integer")
                        .HasColumnName("hex_tile_type");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<int>("Q")
                        .HasColumnType("integer")
                        .HasColumnName("q");

                    b.Property<int>("R")
                        .HasColumnType("integer")
                        .HasColumnName("r");

                    b.Property<int>("S")
                        .HasColumnType("integer")
                        .HasColumnName("s");

                    b.Property<int>("TerrainTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("terrain_type_id");

                    b.HasKey("Id")
                        .HasName("pk_hex_tiles");

                    b.HasIndex("TerrainTypeId")
                        .HasDatabaseName("ix_hex_tiles_terrain_type_id");

                    b.HasIndex("MapId", "Q", "R", "S", "Level")
                        .IsUnique()
                        .HasDatabaseName("ix_hex_tiles_map_id_q_r_s_level");

                    b.ToTable("hex_tiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_HexTile_CubeSum", "q + r + s = 0");
                        });
                });

            modelBuilder.Entity("Solace.Models.HexMaps.SolaceMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MapHeight")
                        .HasColumnType("integer")
                        .HasColumnName("map_height");

                    b.Property<int>("MapLevels")
                        .HasColumnType("integer")
                        .HasColumnName("map_levels");

                    b.Property<int>("MapWidth")
                        .HasColumnType("integer")
                        .HasColumnName("map_width");

                    b.HasKey("Id")
                        .HasName("pk_solace_map");

                    b.ToTable("solace_map", (string)null);
                });

            modelBuilder.Entity("Solace.Models.HexMaps.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EncounterModifier")
                        .HasColumnType("real")
                        .HasColumnName("encounter_modifier");

                    b.Property<float>("EventModifier")
                        .HasColumnType("real")
                        .HasColumnName("event_modifier");

                    b.Property<bool>("IsPassable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float>("TravelModifier")
                        .HasColumnType("real")
                        .HasColumnName("travel_modifier");

                    b.HasKey("Id")
                        .HasName("pk_terrain_types");

                    b.ToTable("terrain_types", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Items.ItemEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectId")
                        .HasColumnType("integer")
                        .HasColumnName("effect_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("Id")
                        .HasName("pk_item_effect");

                    b.HasIndex("EffectId")
                        .HasDatabaseName("ix_item_effect_effect_id");

                    b.HasIndex("ItemId", "EffectId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_effect_item_id_effect_id");

                    b.ToTable("item_effect", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Items.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageBonus")
                        .HasColumnType("integer")
                        .HasColumnName("damage_bonus");

                    b.Property<bool>("IsCursed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cursed");

                    b.Property<bool>("IsEnchanted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enchanted");

                    b.Property<bool>("IsEphemeral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ephemeral");

                    b.Property<bool>("IsRemovable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removable");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("item_type_id");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("integer")
                        .HasColumnName("max_damage");

                    b.Property<int>("MinDamage")
                        .HasColumnType("integer")
                        .HasColumnName("min_damage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("ItemTypeId")
                        .HasDatabaseName("ix_items_item_type_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Items.ItemTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("ElligiblePlacement")
                        .HasColumnType("integer[]")
                        .HasColumnName("elligible_placement");

                    b.Property<bool>("IsLimitedUse")
                        .HasColumnType("boolean")
                        .HasColumnName("is_limited_use");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("PlayerEquippable")
                        .HasColumnType("boolean")
                        .HasColumnName("player_equippable");

                    b.HasKey("Id")
                        .HasName("pk_item_type_model");

                    b.ToTable("item_type_model", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_player_equipment");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_player_equipment_item_id");

                    b.HasIndex("PlayerId", "Placement")
                        .IsUnique()
                        .HasDatabaseName("ix_player_equipment_player_id_placement");

                    b.ToTable("player_equipment", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerStatValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("StatDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_definition_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_player_stat_values");

                    b.HasIndex("StatDefinitionId")
                        .HasDatabaseName("ix_player_stat_values_stat_definition_id");

                    b.HasIndex("PlayerId", "StatDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_stat_values_player_id_stat_definition_id");

                    b.ToTable("player_stat_values", (string)null);
                });

            modelBuilder.Entity("Solace.Models.Player.StatDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stat_definitions");

                    b.ToTable("stat_definitions", (string)null);
                });

            modelBuilder.Entity("Solace.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_token");

                    b.Property<string>("ReplacedByHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Solace.Models.SolaceServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNewUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_new_users");

                    b.Property<string>("CodeOfConduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_of_conduct");

                    b.Property<int>("ConcurrentUserLimit")
                        .HasColumnType("integer")
                        .HasColumnName("concurrent_user_limit");

                    b.Property<int>("DefaultMapHeight")
                        .HasColumnType("integer")
                        .HasColumnName("default_map_height");

                    b.Property<int>("DefaultMapWidth")
                        .HasColumnType("integer")
                        .HasColumnName("default_map_width");

                    b.Property<string>("MapName")
                        .HasColumnType("text")
                        .HasColumnName("map_name");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerTitle")
                        .HasColumnType("text")
                        .HasColumnName("server_title");

                    b.HasKey("Id")
                        .HasName("pk_solace_server");

                    b.ToTable("solace_server", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Solace.Models.Effects.EffectAffectedStat", b =>
                {
                    b.HasOne("Solace.Models.Effects.EffectsModel", "Effect")
                        .WithMany("AffectedStats")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_effect_affected_stats_effects_effect_id");

                    b.HasOne("Solace.Models.Player.StatDefinition", "StatDefinition")
                        .WithMany()
                        .HasForeignKey("StatDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_effect_affected_stats_stat_definitions_stat_definition_id");

                    b.Navigation("Effect");

                    b.Navigation("StatDefinition");
                });

            modelBuilder.Entity("Solace.Models.HexMaps.HexTile", b =>
                {
                    b.HasOne("Solace.Models.HexMaps.SolaceMap", "Map")
                        .WithMany("HexTiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hex_tiles_solace_map_map_id");

                    b.HasOne("Solace.Models.HexMaps.TerrainType", "TerrainType")
                        .WithMany()
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hex_tiles_terrain_types_terrain_type_id");

                    b.Navigation("Map");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("Solace.Models.Items.ItemEffect", b =>
                {
                    b.HasOne("Solace.Models.Effects.EffectsModel", "Effect")
                        .WithMany()
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_effect_effects_effect_id");

                    b.HasOne("Solace.Models.Items.ItemModel", "Item")
                        .WithMany("Effects")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_effect_items_item_id");

                    b.Navigation("Effect");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Solace.Models.Items.ItemModel", b =>
                {
                    b.HasOne("Solace.Models.Items.ItemTypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_item_type_model_item_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerEquipment", b =>
                {
                    b.HasOne("Solace.Models.Items.ItemModel", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_equipment_items_item_id");

                    b.HasOne("Solace.Models.Player.PlayerModel", "Player")
                        .WithMany("EquippedItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_equipment_player_player_id");

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerStatValue", b =>
                {
                    b.HasOne("Solace.Models.Player.PlayerModel", "Player")
                        .WithMany("StatValues")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_stat_values_player_player_id");

                    b.HasOne("Solace.Models.Player.StatDefinition", "StatDefinition")
                        .WithMany()
                        .HasForeignKey("StatDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_stat_values_stat_definitions_stat_definition_id");

                    b.Navigation("Player");

                    b.Navigation("StatDefinition");
                });

            modelBuilder.Entity("Solace.Models.Effects.EffectsModel", b =>
                {
                    b.Navigation("AffectedStats");
                });

            modelBuilder.Entity("Solace.Models.HexMaps.SolaceMap", b =>
                {
                    b.Navigation("HexTiles");
                });

            modelBuilder.Entity("Solace.Models.Items.ItemModel", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Solace.Models.Player.PlayerModel", b =>
                {
                    b.Navigation("EquippedItems");

                    b.Navigation("StatValues");
                });
#pragma warning restore 612, 618
        }
    }
}
